### ISSUE TITLE
A question about nodes for OPC/UA

### ISSUE THREAD

**Issue by schernolyas** [SoftingIndustrial/datafeed-edge-connector#1]
HI!
I need help! I use your image softingindustrial/edgeconnector-840d and I need to test my OPC/UA client. The docker container doesn't provide any OPC/UA nodes .... How I can configure it?

**Comment by sschenk87** [comment]
Hi, there will be OPC UA nodes, if you have sucessfully established a connection to Sinumerik 840D.
If you don't have a NCU/PLC, then please use the image softingindustrial/edgeconnector-siemens:v1-20 and then add one connection, go to the advanced settings and enable the simulation mode. Then you will have a simulated PLC accessible via OPC UA.
BR Sebastian

**Comment by schernolyas** [comment]
HI @sschenk87 
YES!!! Bingo!!! Works !!!!
Thank you very much!!!
