### ISSUE TITLE
Docker image edgeconnector-840d is missing

### ISSUE THREAD

**Issue by phibla** [SoftingIndustrial/datafeed-edge-connector#2]
Hi..i would like to test the edgeconnector for the Siemens 840d but I was not able to pull the docker image. It seems that it is not available on Docker Hub. Will it be online soon? Thanks

**Comment by sschenk87** [comment]
Hello @phibla, thanks for your question. and curiosity. 
It's correct, that the docker image for SINUMERIK 840D is not available at the moment. 
We are working on a different licensing model atm and I will follow up to you when its ready.

Regards,
Sebastian

**Comment by JuergenKosel** [comment]
The image is now available:

`docker pull softingindustrial/edgeconnector-840d`
