### ISSUE TITLE
Support for running docker container of datafeed-edge-connector as non-root

### ISSUE THREAD

**Issue by ripcurlz** [SoftingIndustrial/datafeed-edge-connector#3]
It would be great if there would be the possibility of running the docker container of datafeed-edge-connector as a non-root user out of the box.
This way, security could be improved.

**Comment by JuergenKosel** [comment]
@ripcurlz 

The need to run docker containers as root user or as member of group `docker` (depending on your Linux distribution) comes from the docker daemon.
But you might try to use https://docs.docker.com/engine/security/rootless/

**Comment by ripcurlz** [comment]
@JuergenKosel 
I just realized my question was formulated badly. I did not mean the docker daemon, but the processes running inside the docker container. The link you provided seems to have the solution without the need to create a non-root user during image build. Thanks!
